name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
       

      - name: Build Strapi project
        run: npm run build
        

      - name: Start SSH agent and add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            exec > >(tee -i /tmp/deploy.log)
            exec 2>&1

            echo "Navigating to project directory"
            cd /home/ubuntu/strapi1

            echo "Fixing ownership and permissions"
            sudo chown -R $USER:$USER /home/ubuntu/strapi1
            sudo chown -R $USER:$USER /home/ubuntu/strapi1

            echo "Adding exception for safe directory"
            git config --global --add safe.directory /home/ubuntu/strapi1

            echo "Pulling latest code from main branch"
            git pull origin main

            echo "Fixing npm permissions"
            sudo chown -R $USER:$USER ~/.npm

            echo "Installing dependencies"
            npm install

            echo "Building the project"
            npm run build

            echo "Starting or restarting the application with PM2"
            pm2 start npm --name "strapi-project" -- run start || pm2 restart strapi-project

            echo "Deployment completed"
