# This is a basic workflow to help you get started with Actions

name: CI
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  stop: 
    runs-on: ubuntu-latest
    steps: 
      - name: stop the application
        env: 
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${EC2_KEY}" > private_key.pem
          chmod 600 private_key.pem
          
          echo "Connecting to EC2 instance to stop the application..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            echo "Connected to EC2 instance."
            cd /home/ubuntu/my-project
            echo "Installing pm2 if not present..."
            # sudo npm install -g pm2
            echo "Stopping application with pm2..."
            pm2 stop server
            pm2 delete server
            echo "Application stopped."
          EOF
  # This workflow contains a single job called "build"
 
